Shape added for team with no type determined
TeamTopologies/Team-Shape-Templates pull request #20
Opened 2021-12-17 02:51 UTC by KaranAtTeamForm

By TeamForm

- Update diagrams.net TeamTopologies.xml
- Updated Miro files with new shape
- Updated Images/Screenshots
- Updated PPT with new shape

[CC: ](https://github.com/samuelyeats)
https://github.com/orchestrated-io

2022-01-06 05:11 UTC, conjurer-rich commented
I’m not sure what you are trying to achieve by introducing a “no team type”, can you expand a little?

2022-01-17 03:54 UTC, tkidman commented
> I’m not sure what you are trying to achieve by introducing a “no team type”, can you expand a little?

Hi @conjurer-rich - a bit of background for how this change came about. My team has been building a plugin for Miro that makes use of the Team Topology visual language and concepts. A while back we got to demo this to @matthewskelton. In our plugin we drag teams sourced from our TeamForm app onto a Miro board and then we apply a team topology to these teams, but we didn't know how to represent these teams on the board when a team topology had not yet been selected. We came up with the dotted oval shape as found in this PR. Matthew saw this representation of 'no team type' and said it was almost exactly what he had envisaged, and asked us if we could raise a PR against this repo to add it in. 
In short, 'no team type' is meant to represent a team that has yet to have its team topology defined.  Happy to answer any follow up questions.

Cheers, Tom

2022-01-17 14:28 UTC, conjurer-rich reviewed
Also, see general comment on the PR about moving the Undefined Team Type shape under a different column in the diagrams/tools

2022-01-17 14:28 UTC, conjurer-rich commented on README.md
> +| Team                       |     #EBEBEF     |        0%         |      #9B99AF       |    Dotted     |      2px       |
Change "Team" to "Undefined Team Type"

2022-01-17 14:28 UTC, conjurer-rich commented on README.md
> +- A generic team is team with no team type determined
An undefined team type shape can be used to represent a team that currently has no team type determined

2022-01-17 14:28 UTC, conjurer-rich commented on README.md
> +- Team should always be horizontally aligned with rounded corners and dotted border
An Undefined Team Type team should always be horizontally aligned with rounded corners and dotted border

2022-01-18 05:19 UTC, KaranAtTeamForm commented
@conjurer-rich 

Have pushed the changes based on the comments.

2022-01-20 09:47 UTC, conjurer-rich requested changes
@KaranAtTeamForm why is the canvas.json a binary file, this should be a plain text json file?

2022-01-21 09:17 UTC, merged